/****** Object: Table [SK_F2_FLUSSI].[F2_T_EXP_MappaGruppo_Estesa]   Script Date: 26/02/2018 11.33.34 ******/
USE [PART0];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [SK_F2_FLUSSI].[F2_T_EXP_MappaGruppo_Estesa] (
[Data_estrazione] date NOT NULL,
[Destinazione] nvarchar(10) NOT NULL,
[Codice_Titolo] nvarchar(20) NULL,
[Descrizione_Titolo] nvarchar(200) NULL,
[Codice_Partecipata] nvarchar(16) NULL,
[Denom_Partecipata] nvarchar(150) NULL,
[Tipo_Operazione] nvarchar(5) NULL,
[Codice_Partecipante] nvarchar(16) NULL,
[Denom_Partecipante] nvarchar(150) NULL,
[Ind_Legale_Partecipata] nvarchar(100) NULL,
[Cap_Legale_Partecipata] nvarchar(10) NULL,
[Citta_Legale_Partecipata] nvarchar(100) NULL,
[Prov_Legale_Partecipata] nvarchar(2) NULL,
[Stato_Legale_Partecipata] nvarchar(100) NULL,
[Ex_Art_3639RM] nvarchar(100) NULL,
[Ind_Legale_Partecipante] nvarchar(100) NULL,
[Cap_Legale_Partecipante] nvarchar(10) NULL,
[Citta_Legale_Partecipante] nvarchar(100) NULL,
[Prov_Legale_Partecipante] nvarchar(2) NULL,
[Stato_Legale_Partecipante] nvarchar(100) NULL,
[Valuta_CS_Partecipante] nvarchar(3) NULL,
[CR_Partecipata] nvarchar(16) NULL,
[CF_Partecipata] nvarchar(16) NULL,
[Forma_Giuridica] nvarchar(5) NULL,
[UIC_Partecipata] nvarchar(16) NULL,
[Valuta_Bilancio] nvarchar(3) NULL,
[PIVA_Partecipata] nvarchar(16) NULL,
[Descrizione_ClassBI] nvarchar(100) NULL,
[Descrizione_Attivita] nvarchar(150) NULL,
[SNDG] nvarchar(16) NULL,
[ABI_Prevalente] nvarchar(5) NULL,
[NDG_Prevalente] nvarchar(16) NULL,
[NDG_Capogruppo] nvarchar(16) NULL,
[Gruppo_Bancario] nvarchar(1) NULL,
[Gruppo_Civilistico] nvarchar(1) NULL,
[Gruppo_Assicurativo] nvarchar(1) NULL,
[SAE] nvarchar(6) NULL,
[RAE] nvarchar(6) NULL,
[ATECO] nvarchar(10) NULL,
[Nazionalita] nvarchar(1) NULL,
[Gestore_Partecipazione] nvarchar(100) NULL,
[Quotata] nvarchar(60) NULL,
[Tipo_Quotazione] nvarchar(100) NULL,
[Metodo_ConsBI] nvarchar(100) NULL,
[Metodo_ConsIAS] nvarchar(100) NULL,
[Metodo_ConsFinrep] nvarchar(100) NULL,
[Data_Inserimento] nvarchar(8) NULL,
[Class_IAS_Gruppo] nvarchar(100) NULL,
[Class_Art2359_Gruppo] nvarchar(100) NULL,
[Class_IAS_Individuale] nvarchar(100) NULL,
[Class_Art2359_Individuale] nvarchar(100) NULL,
[Class_Monitoraggio] nvarchar(100) NULL,
[Class_Antitrust] nvarchar(100) NULL,
[Tipologia_FAG] nvarchar(100) NULL,
[Centro_Resp] nvarchar(100) NULL,
[CGU] nvarchar(100) NULL,
[SNDG_ControllataRif] nvarchar(16) NULL,
[Flag_OrgInterposto] nvarchar(1) NULL,
[Flag_OpQualificata] nvarchar(1) NULL,
[Tipo_LookThrough] nvarchar(100) NULL,
[Class_PNF] nvarchar(100) NULL,
[CS_Data] nvarchar(8) NULL,
[CS_Valuta] nvarchar(3) NULL,
[CS_Sottoscritto_Valuta] nvarchar(28) NULL,
[CS_Sottoscritto_Euro] nvarchar(28) NULL,
[CS_Deliberato_Valuta] nvarchar(28) NULL,
[CS_Deliberato_Euro] nvarchar(28) NULL,
[CS_Versato_Valuta] nvarchar(28) NULL,
[CS_Versato_Euro] nvarchar(28) NULL,
[CS_ValNominale_Unitario] nvarchar(28) NULL,
[CS_Azioni] nvarchar(28) NULL,
[CS_AzioniDV] nvarchar(28) NULL,
[CS_AzioniDVAO] nvarchar(28) NULL,
[PATR_ValoreCompl_Valuta] nvarchar(28) NULL,
[PATR_ValoreCompl_Euro] nvarchar(28) NULL,
[PATR_Quote] nvarchar(28) NULL,
[Valuta_Operazione] nvarchar(3) NULL,
[Valore_Civilistico_Valuta] nvarchar(28) NULL,
[Valore_Civilistico_Euro] nvarchar(28) NULL,
[Valore_Prezzo_IAS] nvarchar(28) NULL,
[Valore_NominaleCompl_Divisa] nvarchar(28) NULL,
[Valore_NominaleCompl_Euro] nvarchar(28) NULL,
[Valore_Civilistico_Gruppo] nvarchar(28) NULL,
[Autonomia] nvarchar(100) NULL,
[Azioni_Partecipante] nvarchar(28) NULL,
[Perc_Diretta_Titolo] nvarchar(10) NULL,
[Perc_Diretta_Totale] nvarchar(10) NULL,
[AzioniDV_Partecipante] nvarchar(28) NULL,
[PercDV_Diretta_Titolo] nvarchar(10) NULL,
[PercDV_Diretta_Totale] nvarchar(10) NULL,
[Azioni_Gruppo] nvarchar(28) NULL,
[Perc_Gruppo_Titolo] nvarchar(10) NULL,
[Perc_Gruppo_Totale] nvarchar(10) NULL,
[AzioniDV_Gruppo] nvarchar(28) NULL,
[PercDV_Gruppo_Titolo] nvarchar(10) NULL,
[PercDV_Gruppo_Totale] nvarchar(10) NULL,
[Livello_FairValue] nvarchar(3) NULL,
[Perc_Equity_Ratio] nvarchar(10) NULL,
[Valore_Package] nvarchar(28) NULL,
[Riserva_AFS_Netta] nvarchar(28) NULL,
[Impairment_Anno_Individuale] nvarchar(28) NULL,
[Impairment_Anno_Consolidato] nvarchar(28) NULL,
[Valore_Consolidato] nvarchar(28) NULL,
[Valore_Consolidato_Gruppo] nvarchar(28) NULL,
[Di_Cui_Avviamenti] nvarchar(28) NULL,
[Riserva_AFS_Lorda] nvarchar(28) NULL,
[Delta_Valore_Civilistico] nvarchar(28) NULL,
[Data_Rif_BOFinance] nvarchar(8) NULL,
[Super_ISIN] nvarchar(16) NULL,
[SNDG_Partecipante] nvarchar(16) NULL,
[Perc_SFP_Convertibile] nvarchar(10) NULL,
[Flag_Scarto] bit NOT NULL,
[Motivo_Scarto] nvarchar(2000) NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO


